Adding Scala 2.12.13
sdkman/sdkman-db-migrations pull request #470
Opened 2021-02-15 01:38 UTC by lrlucena

2021-02-15 08:15 UTC, marc0der approved these changes

2021-02-15 08:17 UTC, marc0der requested changes
Looks like the formatting is off. Happy to merge this when the build is green.

2021-02-16 01:08 UTC, lrlucena commented
I formatted the file to have lines with less than 80 characters.

2021-02-16 20:56 UTC, marc0der approved these changes

2021-02-16 20:56 UTC, merged

2021-02-16 20:56 UTC, marc0der commented
Thanks for contributing!