Adding new candidate ActiveMQ (classic)
sdkman/sdkman-db-migrations pull request #525
Opened 2021-07-15 12:05 UTC by xshyamx

Adding new candidate for Apache ActiveMQ (classic)

2021-07-19 19:34 UTC, marc0der requested changes
Thanks for the PR!

One thing, I'd prefer the absolute archive URLs for the artifacts. These dynamic Apache links have caused us many headaches in the past. If you could change this I'd be happy to merge.

2021-07-20 12:51 UTC, xshyamx commented
The archive urls were pretty slow when I was testing so, used the dynamic mirror url. Have reverted to use the apache archive urls

2021-07-20 18:52 UTC, marc0der approved these changes

2021-07-21 12:27 UTC, merged

2021-07-21 12:27 UTC, marc0der commented
Thanks for contributing!