Adding Spark 3.2 and Flink latest version
sdkman/sdkman-db-migrations pull request #605
Opened 2022-07-20 22:01 UTC by chethanuk-plutoflume

2022-07-20 23:21 UTC, eddumelendez commented
Hi @chethanuk-plutoflume, thanks for the PR! We can remove the previous migrations. Can you update the PR, please?

2022-08-16 03:53 UTC, eddumelendez commented
@chethanuk-plutoflume ping

2022-08-16 12:39 UTC, chethanuk-plutoflume commented
> We can remove the previous migrations

will remove with next version

2022-11-16 20:23 UTC, cphbrt requested changes

2022-11-16 20:23 UTC, cphbrt commented on src/main/scala/io/sdkman/changelogs/SparkMigrations.scala
> +    id = "020-add_spark_3.3.1",
This says `3.3.1` whereas line 45 and 46 refer to `3.3.0`.

2022-11-21 18:11 UTC, eddumelendez commented
@chethanuk-plutoflume sorry for the delay. Can you resolve the conflicts, please?

2022-11-22 06:52 UTC, chethanuk-plutoflume commented
> @chethanuk-plutoflume sorry for the delay. Can you resolve the conflicts, please?

Updated

2022-11-22 07:27 UTC, eddumelendez approved these changes

2022-11-22 07:27 UTC, merged