Add Maven 4.0.0-alpha-8
sdkman/sdkman-db-migrations pull request #670
Opened 2023-10-25 14:02 UTC by aalmiray

2023-10-25 14:56 UTC, helpermethod submitted a review, later dismissed
LGTM!

2023-10-25 20:57 UTC, olamy requested changes
Please use maven central url

2023-10-25 21:00 UTC, aalmiray commented
@helpermethod please hold off the merge til I update the URL, thanks.

2023-10-29 16:08 UTC, aalmiray commented
I'm sorry it took so long. The URL has been updated.

cc: @helpermethod

2023-10-29 16:34 UTC, helpermethod commented on src/main/scala/io/sdkman/changelogs/MavenMigration.scala
> +      "https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/4.0.0-alpha-8/apache-maven-4.0.0-alpha-8-bin.zipp"
That should be `.zip` not `.zipp` 😄

2023-10-29 16:41 UTC, aalmiray commented on src/main/scala/io/sdkman/changelogs/MavenMigration.scala
> +      "https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/4.0.0-alpha-8/apache-maven-4.0.0-alpha-8-bin.zipp"
Fixed 😅

2023-10-29 18:15 UTC, helpermethod approved these changes
LGTM!

2023-10-29 18:16 UTC, merged