Add Jeka candidate
sdkman/sdkman-db-migrations pull request #718
Opened 2024-12-19 18:44 UTC by djeang

2025-01-04 13:46 UTC, marc0der commented on src/main/scala/io/sdkman/changelogs/JekaMigrations.scala
> +      name = "Jeka",
JeKa?

2025-01-04 13:50 UTC, marc0der commented on src/main/scala/io/sdkman/changelogs/JekaMigrations.scala
> +        "Jeka is a build tool for Java focusing on simplicity.",
```suggestion
        "JeKa is a modern build tool for Java, designed to simplify and streamline your development experience. It reshapes Java application building for a generation of developers seeking lightweight, accessible, yet powerful solutions."
```

This description is used on our website and when you run `sdk list` (as is the `name`  attribute above), so we need a bit more verbosity.

2025-01-04 13:53 UTC, marc0der requested changes
The `name` and `description` are used on our website and when you run `sdk list` so we need a bit more verbosity and uniformity.

2025-01-04 13:54 UTC, marc0der commented on src/main/scala/io/sdkman/changelogs/JekaMigrations.scala
> +      name = "Jeka",
```suggestion
      name = "JeKa",
```

2025-01-12 15:25 UTC, djeang commented
I’ve fixed the website URL as well. The description looks good to me. I think we can move forward.

Thank you!

2025-03-15 14:03 UTC, marc0der commented
Apologies, I totally missed your changes back in December and forgot about this PR. Would you like me to merge that now @djeang?

2025-03-15 14:03 UTC, marc0der approved these changes

2025-06-24 07:21 UTC, djeang commented
Hi Marc, sorry for this delay, too. I was focused on improving the product itself. I'm now ready to follow up the SdkMan onboarding. Can you merge the request please?

2025-07-01 08:02 UTC, merged